version: '3'

services:
  clean-hotel-backend:
    build: .
    environment:
      API_PORT: ${API_PORT}
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${API_PORT}:${API_PORT}"
